version: "3.9"
services:
  test:
    image: mcr.microsoft.com/planetary-computer/python:2022.05.11.0
    # command: ./scripts/start pytest -vs
    command: /bin/bash
    working_dir: /home/jovyan/etl
    volumes:
      - .:/home/jovyan/etl
    env_file:
      - .env
  cache-quads:
    image: mcr.microsoft.com/planetary-computer/python:2022.05.11.0
    command: python /code/quads.py --file="https://planet.blob.core.windows.net/nicfi-etl-data/aois/planet_areas_brazil_amazonia.zip"
    volumes:
      - .:/code
    env_file:
      - .env
  extract:
    image: mcr.microsoft.com/planetary-computer/python:2022.05.11.0
    # command: python /code/main.py --start-datetime=2020-01-01 --end-datetime=2022-04-02 --file=/code/aois/planet_areas_brazil_amazonia.zip
    command: python stactools_nicfi_etl/etl.py --start-datetime=2020-01-01 --end-datetime=2022-05-02 --file="https://planet.blob.core.windows.net/nicfi-etl-data/aois/planet_areas_brazil_amazonia.zip"
    volumes:
      - .:/code
    env_file:
      - .env
  console:
    image: mcr.microsoft.com/planetary-computer/python:2022.05.11.0
    command: /bin/bash
    working_dir: /home/jovyan/etl
    volumes:
      - .:/home/jovyan/etl
    env_file:
      - .env
